### PR TITLE
WIP OS X Compatibility

### PR DESCRIPTION
**Pull request by samsiegart**

### CODE REVIEW

**Comment by dpclark4** [comment]
What version of osx are you currently running? I am getting the following error: src//lib/fontstash/fontstash.cpp:25:10: fatal error: 'GL/glew.h' file not found
#include <GL/glew.h>  /* @rlyeh: before including GL. doesnt hurt and makes life better */

I tried a while ago to get this program to work natively on osx, but I was not successful. I think I might have gotten far enough for it to compile completely.

**Comment by samsiegart** [comment]
I was using 10.10.5

Do you have Homebrew installed? If so, try `brew install homebrew/x11/freeglut` and `brew install glew` and see if it allows it to compile afterwards.

Also, you will have to edit `src/sim/Directory.cpp` to include the absolute path for your system, as it's currently hardcoded for mine.

It currently compiles on my computer but the shaders do not work so the polygons do not get drawn to the screen yet.

**Comment by dpclark4** [comment]
Dan:~/Programming/mms> brew install homebrew/x11/freeglut
Warning: homebrew/x11/freeglut-2.8.1 already installed
Dan:~/Programming/mms> brew install glew
Warning: glew-1.12.0 already installed

When I got this compile last time I installed them. I changed the path variable in Directory.cpp and still have the same issue issue aboe. When I was last working on this, I thought I came across some changes that might have affected the jump from 10.9 to 10.10 or 10.10 to 10.11 (I couldn't remember). Must have been the latter of the two as I am on 10.11.4.

**Comment by samsiegart** [comment]
The only other thing I can think of is the makefile. Try changing the appropriate line from:
```
#Dynamically linked libraries
LIBS = -lGLEW -lGL -lglut -lGLU -lpthread
```
To:
```
#Dynamically linked libraries
LIBS = -lGLEW -framework GLUT -framework OpenGL -lglut -lpthread
```

**Comment by samsiegart** [comment]
Also, my glew says version 1.13.0 not 1.12.0, maybe upgrading it would help

**Pull request merged**
